<?php
// Set proper headers for PDF output
header('Content-Type: application/pdf');
header('Cache-Control: private, max-age=0, must-revalidate');
header('Pragma: public');

// Prevent any HTML output
ob_start();

require_once "../config.php";
require_once "../apiPPMP/token_helper.php";

TokenHelper::init($conn);

// Check if FPDF library exists
$fpdf_path = __DIR__ . "/fpdf186/fpdf.php";
if (!file_exists($fpdf_path)) {
    // Clear any output buffers
    while (ob_get_level()) {
        ob_end_clean();
    }

    // Create error PDF without FPDF
    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="error.pdf"');

    // Simple PDF creation without FPDF
    echo "%PDF-1.4\n";
    echo "1 0 obj\n";
    echo "<<\n";
    echo "/Type /Catalog\n";
    echo "/Pages 2 0 R\n";
    echo ">>\n";
    echo "endobj\n";
    echo "2 0 obj\n";
    echo "<<\n";
    echo "/Type /Pages\n";
    echo "/Kids [3 0 R]\n";
    echo "/Count 1\n";
    echo ">>\n";
    echo "endobj\n";
    echo "3 0 obj\n";
    echo "<<\n";
    echo "/Type /Page\n";
    echo "/Parent 2 0 R\n";
    echo "/MediaBox [0 0 612 792]\n";
    echo "/Contents 4 0 R\n";
    echo "/Resources <<\n";
    echo "/Font <<\n";
    echo "/F1 5 0 R\n";
    echo ">>\n";
    echo ">>\n";
    echo ">>\n";
    echo "endobj\n";
    echo "4 0 obj\n";
    echo "<<\n";
    echo "/Length 44\n";
    echo ">>\n";
    echo "stream\n";
    echo "BT\n";
    echo "/F1 12 Tf\n";
    echo "100 700 Td\n";
    echo "(FPDF Library Not Found) Tj\n";
    echo "ET\n";
    echo "endstream\n";
    echo "endobj\n";
    echo "5 0 obj\n";
    echo "<<\n";
    echo "/Type /Font\n";
    echo "/Subtype /Type1\n";
    echo "/BaseFont /Helvetica\n";
    echo ">>\n";
    echo "endobj\n";
    echo "xref\n";
    echo "0 6\n";
    echo "0000000000 65535 f \n";
    echo "0000000009 00000 n \n";
    echo "0000000058 00000 n \n";
    echo "0000000115 00000 n \n";
    echo "0000000274 00000 n \n";
    echo "0000000368 00000 n \n";
    echo "trailer\n";
    echo "<<\n";
    echo "/Size 6\n";
    echo "/Root 1 0 R\n";
    echo ">>\n";
    echo "startxref\n";
    echo "462\n";
    echo "%%EOF\n";
    exit();
}

require_once "fpdf186/fpdf.php";

// Extend FPDF class for APP-CSE form
class APPCSEPDF extends FPDF {
    public $currentYear;

    function __construct($orientation = 'P', $unit = 'mm', $size = 'A4', $currentYear = null) {
        $this->currentYear = $currentYear ?: date('Y');
        parent::__construct($orientation, $unit, $size);
    }

    function Header() {
        if ($this->PageNo() == 1) {
            // Logo on the left
            $logoPath = __DIR__ . '/image/citylogo.png';
            if (file_exists($logoPath)) {
                $this->Image('image/citylogo.png', 10, 8, 15);
            }

            // Government header
            $this->SetFont('Arial', 'B', 12);
            $this->SetTextColor(0, 51, 102);
            $this->Cell(0, 6, 'Republic of the Philippines', 0, 1, 'C');
            $this->SetFont('Arial', 'B', 10);
            $this->Cell(0, 5, 'Province of Bukidnon', 0, 1, 'C');
            $this->SetFont('Arial', 'B', 9);
            $this->Cell(0, 4, 'City of Malaybalay', 0, 1, 'C');

            // Logo on the right
            if (file_exists($logoPath)) {
                $this->Image('image/citylogo.png', 320, 8, 15);
            }

            // Main title
            $this->Ln(2);
            $this->SetFont('Arial', 'B', 10);
            $this->SetTextColor(0, 0, 0);
            $this->Cell(0, 6, 'ANNUAL PROCUREMENT PLAN - COMMON-USE SUPPLIES AND EQUIPMENT (APP-CSE)', 0, 1, 'C');
            $this->SetFont('Arial', 'B', 9);
            $this->Cell(0, 5, $this->currentYear . ' FORM', 0, 1, 'C');

            $this->Ln(3);
        }
    }

    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(128, 128, 128);
        $this->Cell(0, 5, 'Generated by PPMP Management System - Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'C');
    }

    function NbLines($w, $txt) {
        $cw = &$this->CurrentFont['cw'];
        if($w==0)
            $w = $this->w - $this->rMargin - $this->x;
        $wmax = ($w-2*$this->cMargin)*1000/$this->FontSize;
        $s = str_replace("\r", '', $txt);
        $nb = strlen($s);
        if($nb>0 && $s[$nb-1]=="\n")
            $nb--;
        $sep = -1;
        $i = 0;
        $j = 0;
        $l = 0;
        $nl = 1;
        while($i<$nb) {
            $c = $s[$i];
            if($c=="\n") {
                $i++;
                $sep = -1;
                $j = $i;
                $l = 0;
                $nl++;
                continue;
            }
            if($c==' ')
                $sep = $i;
            $l += isset($cw[$c]) ? $cw[$c] : 0;
            if($l>$wmax) {
                if($sep==-1) {
                    if($i==$j)
                        $i++;
                } else
                    $i = $sep+1;
                $sep = -1;
                $j = $i;
                $l = 0;
                $nl++;
            } else
                $i++;
        }
        return $nl;
    }

    // Agency information section
    function AgencyInfo() {
        $this->SetFont('Arial', 'B', 8);
        $this->SetTextColor(0, 0, 0);

        // Create a table-like structure for agency info
        $this->Cell(35, 5, 'Department/Bureau/Office:', 1, 0, 'L');
        $this->Cell(55, 5, 'CITY ADMINISTRATORS OFFICE', 1, 0, 'L');
        $this->Cell(30, 5, 'Agency Code/UACS:', 1, 0, 'L');
        $this->Cell(50, 5, '1.01.01.01.01', 1, 1, 'L');

        $this->Cell(35, 5, 'Region:', 1, 0, 'L');
        $this->Cell(55, 5, 'REGION X', 1, 0, 'L');
        $this->Cell(30, 5, 'Organization Type:', 1, 0, 'L');
        $this->Cell(50, 5, 'Local Government Unit', 1, 1, 'L');

        $this->Cell(35, 5, 'Address:', 1, 0, 'L');
        $this->Cell(55, 5, 'Malaybalay City, Bukidnon', 1, 0, 'L');
        $this->Cell(30, 5, 'Contact Person:', 1, 0, 'L');
        $this->Cell(50, 5, 'TEOFILO A. PIODOS JR', 1, 1, 'L');

        $this->Cell(35, 5, 'E-mail:', 1, 0, 'L');
        $this->Cell(55, 5, 'cao@malaybalaycity.gov.ph', 1, 0, 'L');
        $this->Cell(30, 5, 'Position:', 1, 0, 'L');
        $this->Cell(50, 5, 'City Administrator', 1, 1, 'L');

        $this->Cell(35, 5, 'Telephone/Mobile Nos:', 1, 0, 'L');
        $this->Cell(140, 5, '(088) 813-5123 / 0918-123-4567', 1, 1, 'L');

        $this->Ln(3);
    }

    // Introduction section
    function Introduction() {
        $this->SetFont('Arial', '', 7);
        $this->SetTextColor(0, 0, 0);

        $this->Cell(0, 4, 'Introduction:', 0, 1, 'L');
        $this->MultiCell(0, 3, 'This form contains the common-use supplies and equipment (CSE) being carried by the Procurement Service - Department of Budget and Management (PS-DBM) that shall be purchased by government agencies. Consistent with the DBM Circular Letter Nos. 2011-6 and 2011-6-A dated 25 August 2011 and 28 September 2011, respectively, the APP-CSE shall serve as the agency\'s annual procurement request for all its CSE requirements. Only agencies with uploaded APP-CSE in the Modernized Philippine Government Electronic Procurement System (mPhilGEPS) will be able to purchase CSE from the PS-DBM. Note that the items listed on this form have been arranged in accordance with the United Nations Standard Products and Services Code (UNSPSC).', 0, 'L');

        $this->Ln(2);
    }

    // Table header for APP-CSE format
    function TableHeader() {
        $this->SetFont('Arial', 'B', 6);
        $this->SetFillColor(200, 200, 200);
        $this->SetTextColor(0, 0, 0);

        // Multi-row header
        $this->Cell(18, 10, 'Item Code', 1, 0, 'C', true);
        $this->Cell(55, 10, 'Item & Specifications', 1, 0, 'C', true);
        $this->Cell(8, 10, 'Unit of Measure', 1, 0, 'C', true);

        // Monthly columns - spanning header
        $this->Cell(120, 5, 'Monthly Quantity Requirement', 1, 0, 'C', true);
        $this->Cell(30, 10, 'Total Quantity for the year', 1, 0, 'C', true);
        $this->Cell(35, 10, 'Unit Price as of May 14, 2025', 1, 0, 'C', true);
        $this->Cell(35, 10, 'Total Amount for the year', 1, 1, 'C', true);

        // Second row of header
        $this->SetXY(10, $this->GetY() - 5);
        $this->Cell(81, 5, '', 0, 0); // Skip first 3 columns (18+55+8=81)

        $months = array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
        foreach($months as $month) {
            $this->Cell(10, 5, $month, 1, 0, 'C', true);
        }
        $this->Ln(5);
    }

    // Table row
    function TableRow($data) {
        $this->SetFont('Arial', '', 5);
        $this->SetTextColor(0, 0, 0);

        $widths = array(18, 55, 8, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 30, 35, 35);

        // Calculate max lines for the row
        $max_lines = 1;
        for($i = 0; $i < count($data); $i++) {
            $lines = $this->NbLines($widths[$i], $data[$i]);
            $max_lines = max($max_lines, $lines);
        }
        $height = $max_lines * 4;

        $startY = $this->GetY();
        for($i = 0; $i < count($data); $i++) {
            $x = $this->GetX();
            $align = ($i >= 3 && $i <= 14) ? 'C' : 'L';
            $this->MultiCell($widths[$i], 4, $data[$i], 1, $align);
            $this->SetXY($x + $widths[$i], $startY);
        }
        $this->Ln($height);
    }

    // Summary section
    function SummarySection($totalAmount) {
        $this->Ln(3);
        $this->SetFont('Arial', 'B', 8);
        $this->Cell(0, 6, 'PART I. AVAILABLE AT PS-DBM (MAIN WAREHOUSE AND DEPOTS)', 0, 1, 'L');

        $this->SetFont('Arial', '', 7);
        $this->Cell(70, 5, 'A. TOTAL', 1, 0, 'L');
        $this->Cell(25, 5, 'P' . number_format($totalAmount, 2), 1, 1, 'R');

        $inflation = $totalAmount * 0.1;
        $this->Cell(70, 5, 'B. ADDITIONAL PROVISION FOR INFLATION (10% of TOTAL)', 1, 0, 'L');
        $this->Cell(25, 5, 'P' . number_format($inflation, 2), 1, 1, 'R');

        $this->Cell(70, 5, 'C. ADDITIONAL PROVISION FOR TRANSPORT AND FREIGHT COST (If Applicable)', 1, 0, 'L');
        $this->Cell(25, 5, 'P0.00', 1, 1, 'R');

        $grandTotal = $totalAmount + $inflation;
        $this->Cell(70, 5, 'D. GRAND TOTAL (A + B + C)', 1, 0, 'L');
        $this->Cell(25, 5, 'P' . number_format($grandTotal, 2), 1, 1, 'R');

        $this->Ln(2);
        $this->Cell(70, 5, 'E. APPROVED BUDGET BY THE AGENCY HEAD', 1, 0, 'L');
        $this->Cell(25, 5, '', 1, 1, 'R');
        $this->Cell(70, 5, 'In Figures and Words:', 1, 0, 'L');
        $this->Cell(25, 5, '', 1, 1, 'R');
    }

    // Signature section
    function SignatureSection() {
        $this->Ln(8);
        $this->SetFont('Arial', '', 7);

        // Prepared by section
        $this->Cell(55, 5, 'Prepared by:', 0, 0, 'L');
        $this->Cell(55, 5, 'Certified Funds Available / Certified Appropriate Funds Available:', 0, 0, 'C');
        $this->Cell(55, 5, 'Approved by:', 0, 1, 'R');

        $this->Ln(2);
        $this->Cell(55, 6, 'Property/Supply Officer', 'T', 0, 'C');
        $this->Cell(55, 6, 'Accountant / Budget Officer', 'T', 0, 'C');
        $this->Cell(55, 6, 'Head of Office/Agency', 'T', 1, 'C');

        $this->Ln(3);
        $this->Cell(55, 5, 'Date Prepared: _______________', 0, 0, 'L');
        $this->Cell(55, 5, 'Date: _______________', 0, 0, 'C');
        $this->Cell(55, 5, 'Date: _______________', 0, 1, 'R');
    }
}

// Temporarily disable authentication for testing
// Check if user is logged in with session (for direct access) or JWT token
/*

if (isset(null)) {
    // User is logged in via session, allow access
} else {
    // Check JWT token
    if (function_exists('apache_request_headers')) {
        $headers = apache_request_headers();
        $authHeader = $headers['Authorization'] ?? '';
    } else {
        $authHeader = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
    }
    // Fallback to token in query parameter for GET requests
    if (empty($authHeader) && $_SERVER['REQUEST_METHOD'] === 'GET') {
        $authHeader = 'Bearer ' . ($_GET['token'] ?? '');
    }

    $token = RedisHelper::extractTokenFromHeader($authHeader);

    if (!$token) {
        // For PDF output, don't redirect - show error in PDF
        $pdf = new APPCSEPDF('P', 'mm', 'Legal');
        $pdf->AddPage();
        $pdf->SetFont('Arial', 'B', 16);
        $pdf->SetTextColor(255, 0, 0);
        $pdf->Cell(0, 20, 'Access Denied: Please log in first', 0, 1, 'C');
        $pdf->Output('Access_Denied.pdf', 'I');
        exit();
    }

    $tokenValidation = RedisHelper::validateAccessToken($token);
    if (!$tokenValidation['valid']) {
        // For PDF output, don't redirect - show error in PDF
        $pdf = new APPCSEPDF('P', 'mm', 'Legal');
        $pdf->AddPage();
        $pdf->SetFont('Arial', 'B', 16);
        $pdf->SetTextColor(255, 0, 0);
        $pdf->Cell(0, 20, 'Access Denied: Invalid or expired token', 0, 1, 'C');
        $pdf->Output('Access_Denied.pdf', 'I');
        exit();
    }
}
*/

// Check if preview mode is requested
$preview = isset($_GET['preview']) && $_GET['preview'] == '1';

// Get the year from PPMP documents first
$yearStmt = $conn->prepare("SELECT DISTINCT Plan_Year FROM tbl_ppmp_documents WHERE Status = 'approved' ORDER BY Plan_Year DESC LIMIT 1");
$yearStmt->execute();
$yearResult = $yearStmt->fetch(PDO::FETCH_ASSOC);
$currentYear = $yearResult ? $yearResult['Plan_Year'] : date('Y');

// Check if there are any approved PPMP documents
$checkStmt = $conn->prepare("SELECT COUNT(*) as count FROM tbl_ppmp_documents WHERE Status = 'approved'");
$checkStmt->execute();
$checkResult = $checkStmt->fetch(PDO::FETCH_ASSOC);
$approvedCount = $checkResult['count'];

// Create PDF in landscape orientation for APP-CSE form
$pdf = new APPCSEPDF('L', 'mm', 'Legal', $currentYear);
$pdf->AliasNbPages();
$pdf->AddPage();

// Agency information
$pdf->AgencyInfo();

// Introduction
$pdf->Introduction();

// Check if there are approved PPMP documents
if ($approvedCount == 0) {
    // Create error PDF for no approved documents
    $pdf = new APPCSEPDF('L', 'mm', 'Legal', $currentYear);
    $pdf->AddPage();
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetTextColor(255, 0, 0);
    $pdf->Cell(0, 20, 'No Approved PPMP Documents Found', 0, 1, 'C');
    $pdf->SetFont('Arial', '', 12);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->MultiCell(0, 10, 'The APP report requires approved PPMP documents to generate procurement data. Please ensure you have PPMP documents with "approved" status before generating the report.', 0, 'L');
    $pdf->Ln(10);
    $pdf->Cell(0, 10, 'Contact your system administrator if you need assistance.', 0, 1, 'L');

    // Output PDF
    $filename = 'APP_Report_Error_' . date('Y-m-d_H-i-s') . '.pdf';
    if ($preview) {
        $pdf->Output($filename, 'I');
    } else {
        $pdf->Output($filename, 'D');
    }
    exit();
}

// Get consolidated items data with monthly breakdown
try {
    $stmt = $conn->prepare("
        SELECT
            e.Item_Code,
            e.Item_Name,
            e.Item_Description,
            e.Unit,
            e.Unit_Cost,
            i.Category,
            SUM(e.Jan_Qty) as jan_qty,
            SUM(e.Feb_Qty) as feb_qty,
            SUM(e.Mar_Qty) as mar_qty,
            SUM(e.Apr_Qty) as apr_qty,
            SUM(e.May_Qty) as may_qty,
            SUM(e.Jun_Qty) as jun_qty,
            SUM(e.Jul_Qty) as jul_qty,
            SUM(e.Aug_Qty) as aug_qty,
            SUM(e.Sep_Qty) as sep_qty,
            SUM(e.Oct_Qty) as oct_qty,
            SUM(e.Nov_Qty) as nov_qty,
            SUM(e.Dec_Qty) as dec_qty,
            SUM(e.Total_Qty) as total_quantity,
            SUM(e.Total_Cost) as total_cost,
            COUNT(DISTINCT e.PPMP_ID) as ppmp_count,
            GROUP_CONCAT(DISTINCT p.PPMP_Number ORDER BY p.PPMP_Number SEPARATOR ', ') as ppmp_numbers
        FROM tbl_ppmp_entries e
        INNER JOIN tbl_ppmp_documents p ON e.PPMP_ID = p.ID
        INNER JOIN tbl_ppmp_bac_items i ON e.Item_ID = i.ID
        WHERE p.Status = 'approved' AND p.Plan_Year = ?
        GROUP BY e.Item_Code, e.Item_Name, e.Item_Description, e.Unit, e.Unit_Cost, i.Category
        ORDER BY i.Category, e.Item_Code, e.Item_Name
    ");
    $stmt->execute([$currentYear]);
    $items = $stmt->fetchAll(PDO::FETCH_ASSOC);

    // Check if there are any items
    if (empty($items)) {
        // Create error PDF for no items data
        $pdf = new APPCSEPDF('L', 'mm', 'Legal', $currentYear);
        $pdf->AddPage();
        $pdf->SetFont('Arial', 'B', 16);
        $pdf->SetTextColor(255, 0, 0);
        $pdf->Cell(0, 20, 'No Procurement Items Found', 0, 1, 'C');
        $pdf->SetFont('Arial', '', 12);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->MultiCell(0, 10, 'The approved PPMP documents do not contain any procurement items. Please ensure your PPMP documents have been properly created with items before generating the APP report.', 0, 'L');
        $pdf->Ln(10);
        $pdf->Cell(0, 10, 'Approved PPMP documents found: ' . $approvedCount, 0, 1, 'L');
        $pdf->Cell(0, 10, 'Year: ' . $currentYear, 0, 1, 'L');

        // Output PDF
        $filename = 'APP_Report_No_Items_' . date('Y-m-d_H-i-s') . '.pdf';
        if ($preview) {
            $pdf->Output($filename, 'I');
        } else {
            $pdf->Output($filename, 'D');
        }
        exit();
    }

    // Group items by category
    $groupedItems = [];
    foreach($items as $item) {
        $category = $item['Category'] ?: 'Uncategorized';
        if (!isset($groupedItems[$category])) {
            $groupedItems[$category] = [];
        }
        $groupedItems[$category][] = $item;
    }

    // Calculate totals
    $totalValue = 0;
    foreach($items as $item) {
        $totalValue += $item['total_cost'];
    }

    // Table header
    $pdf->TableHeader();

    // Table data
    $counter = 1;
    foreach($groupedItems as $category => $categoryItems) {
        // Category header
        $pdf->SetFont('Arial', 'B', 7);
        $pdf->SetFillColor(240, 240, 240);
        $pdf->Cell(0, 8, strtoupper($category), 1, 1, 'L', true);

        foreach($categoryItems as $item) {
            $data = array(
                $item['Item_Code'] ?: '',
                $item['Item_Name'] . ' - ' . $item['Item_Description'],
                $item['Unit'] ?: '',
                $item['jan_qty'] > 0 ? $item['jan_qty'] : '',
                $item['feb_qty'] > 0 ? $item['feb_qty'] : '',
                $item['mar_qty'] > 0 ? $item['mar_qty'] : '',
                $item['apr_qty'] > 0 ? $item['apr_qty'] : '',
                $item['may_qty'] > 0 ? $item['may_qty'] : '',
                $item['jun_qty'] > 0 ? $item['jun_qty'] : '',
                $item['jul_qty'] > 0 ? $item['jul_qty'] : '',
                $item['aug_qty'] > 0 ? $item['aug_qty'] : '',
                $item['sep_qty'] > 0 ? $item['sep_qty'] : '',
                $item['oct_qty'] > 0 ? $item['oct_qty'] : '',
                $item['nov_qty'] > 0 ? $item['nov_qty'] : '',
                $item['dec_qty'] > 0 ? $item['dec_qty'] : '',
                number_format($item['total_quantity']),
                'P' . number_format($item['Unit_Cost'], 2),
                'P' . number_format($item['total_cost'], 2)
            );
            $pdf->TableRow($data);

            // Check if we need a new page
            if($pdf->GetY() > 170) {
                $pdf->AddPage();
                $pdf->TableHeader();
            }
        }
    }

    // Summary section
    $pdf->SummarySection($totalValue);

    // Signature section
    $pdf->SignatureSection();

    // Reminders section
    $pdf->Ln(8);
    $pdf->SetFont('Arial', 'B', 7);
    $pdf->Cell(0, 4, 'Reminders:', 0, 1, 'L');
    $pdf->SetFont('Arial', '', 6);
    $pdf->MultiCell(0, 2.5, "1. The APP-CSE form must be accomplished using Microsoft Excel format. The APP-CSE shall be deemed incorrect or invalid if the form used is other than the prescribed format which is downloadable from the mPhilGEPS and Downloads page of PS-DBM website (www.ps-philgeps.gov.ph).\n\n2. All information must be provided accurately.\n\n3. Kindly refer to the CSE catalogue on the PS-DBM website (www.ps-philgeps.gov.ph) under the 'What We Sell' tab for the detailed technical specifications and sample photo of the items.\n\n4. Do not delete, add, or revise any items or rows on this form, otherwise the form will be deemed invalid.\n\n5. Once signed and approved by the Property/Supply Officer, Accountant/Budget Officer, and Head of the Agency/Office, kindly upload the soft copy of the APP-CSE in Microsoft Excel format as well as the original signed copy in Portable Document Format (PDF) to the agency's mPhilGEPS account on or before the prescribed period or deadline. Any APP-CSE form that is unsigned or has incomplete signature shall be deemed invalid.\n\n6. Should there be changes in the agency's CSE requirements, the agency may edit their uploaded APP-CSE directly on their mPhilGEPS account. However, the agency must ensure that a signed and approved copy of the supplemental APP-CSE form is available. Note that all CSE requirements in excess of the quantities indicated in the original APP-CSE form will not be served if not covered by a supplemental APP-CSE.\n\n7. Please be advised that modifications to product codes may be implemented without prior notification. Should such changes occur, it will be necessary for agencies with CSE requirements to edit and submit a Supplemental APP-CSE on their mPhilGEPS account.\n\n8. For further assistance or clarification, agencies may contact the Marketing and Sales Division of PS-DBM through its mobile numbers 0918-2954426 (Smart) or 0962-8255199 (Smart), or email appcse.helpdesk@ps-philgeps.gov.ph, or visit the PS-DBM website (www.ps-philgeps.gov.ph) for the guide on how to fill-out the APP-CSE.\n\n9. Note: The APP-CSE for FY " . ($currentYear + 1) . " must be submitted on or before 31 August " . $currentYear . ".", 0, 'L');

} catch (Exception $e) {
    // Clear any output buffers
    while (ob_get_level()) {
        ob_end_clean();
    }

    // Create error PDF
    $pdf = new APPCSEPDF('P', 'mm', 'Legal');
    $pdf->AddPage();
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetTextColor(255, 0, 0);
    $pdf->Cell(0, 20, 'Error Generating APP-CSE Report', 0, 1, 'C');
    $pdf->SetFont('Arial', '', 12);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->MultiCell(0, 10, 'An error occurred while generating the PDF report: ' . $e->getMessage(), 0, 'L');
    $pdf->Ln(10);
    $pdf->Cell(0, 10, 'Please contact your system administrator.', 0, 1, 'L');
}

// Output PDF based on mode
$filename = 'Annual_Procurement_Plan_Report_' . date('Y-m-d_H-i-s') . '.pdf';

if ($preview) {
    // Preview mode - display in browser
    $pdf->Output($filename, 'I');
} else {
    // Download mode - force download
    $pdf->Output($filename, 'D');
}
?>
